name: iptv_check_manager
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: '>=0.13.0 <=0.13.5'
  m3u:
    git: https://github.com/uiiang/m3u-parse-utils.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
